version: '3.8'

services:
  armadacms:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3254:3254
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      API_PORT: 3254
      DB_USER: postgres
      DB_PASSWORD: secret
      DB_NAME: armadacms
      DB_SSLMODE: disable

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: armadacms
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
